Auto/Controllers/RegisterController.cs
using Auto.Models;
using Auto.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.AccessControl;

namespace Auto.Controllers
{
  public class RegisterController : Controller
  {
    private readonly ILogger<RegisterController> _logger;
    private readonly AddObject _addobj;    

    public RegisterController(ILogger<RegisterController> logger, AddObject addObject)
    {
      _logger = logger;
      _addobj = addObject;
    }
    [HttpGet]
    public IActionResult Index()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Authenfic([FromForm] string login, [FromForm] string password)
    {
      var user = _addobj.GetUserFirst(login);
      if (user == null)
      {
        ViewBag.Error = "Пользователь не найден!";
        return View("Index");
      }
      if (user.Password == password)
      {        
        switch (user.Role.RoleName)
        {
          case "Client":
            _addobj.WriteUserId(user.UserId);
            return RedirectToAction("Auto", "Users");
          case "Employee":
            _addobj.WriteUserId(user.UserId);
            return RedirectToAction("Applic", "Employee");
          default:
            ViewBag.ErrorAut = "Неверный логин или пароль";
            return View("Index");
        }
      }
      else
      {
        ViewBag.Error = "Неверный пароль!";
        return View("Index");
      }

    }
  }
}

Auto/Views/Register/Index.cshtml
@{
    ViewData["Title"] = "Login";
}


@*<h1>@ViewData["Title"]</h1>
<br>*@
<form asp-controller="Register" asp-action="Authenfic" method="post">
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" placeholder="Login" name="login">
                <label for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" class="form-control" placeholder="Password" name="password">
                <label for="floatingInput">Password</label>
            </div>
        </div>
    </div>
    @if (ViewBag.Error != null)
    {
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning" role="alert">
               @ViewBag.Error
            </div>
        </div>
    </div>
    }
</div>

<br /> <button type="submit" class="btn btn-outline-primary">Login</button>

</form>